### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Bruno-Furtado** [graffiti75/TwitterApiTest#1]
Olá @graffiti75,

Gostaríamos de agradecer pelo tempo dedicado. 😃 
Vamos aguardar os outros candidatos finalizarem seus testes para o envio de um feedback final.

Por enquanto, segue a lista com os resultados obtidos a partir das especificações.
Abraços.

---
### Telas
- Home
  - [x] Campo de busca
  - [ ] Lista com as últimas pesquisas feitas dentro do app
  - [ ] Trending do Twitter (bônus)
- Resultados
  - [ ] Barra com o texto pesquisado
  - [x] Lista com os resultados (cada item deve possuir o texto, o nome e a imagem do usuário)
### Requisitos
- [x] Java
- [x] Android Studio
- [ ] SDK 4.0+
- [x] Portrait
- [x] Universal
- [x] Suportar no mínimo 2 idiomas

---

**Especificações atendidas:** 7/11

**Comment by graffiti75** [comment]
Olá @Bruno-Furtado .

Corrigi o aplicativo com as informações que faltavam.

**Comment by Bruno-Furtado** [comment]
@graffiti75,
Após uma segunda tentativa, todos as especificações foram atendidas. 😃 

---

### Observações

**1.** Ao solicitar a lista com as últimas pesquisas dentro do app deixamos subentendido que o histórico deve ser persistido em um banco de dados local, para que, ao matar o app e abri-lo novamente, o usuário tenha acesso aos itens pesquisados anteriormente. De qualquer forma a solução implementada salva os itens em memória e mostra conhecimento técnico pois utiliza o padrão de projeto Singleton. Em um cenário real, esta não seria a solução ideal mas entendemos que a especificação pode não ter sido clara suficiente portanto consideramos o item como implementado.

**2.** Tanto o histórico de pesquisa quanto trending do Twitter foram implementados. Num cenário real, esperavamos que, ao tocar em um item da lista, o usuário visualizasse os tweets relacionados. De qualquer forma, o requisito foi seguido a risca e implementado.

**3.** Para ter acesso ao histórico de pesquisa, o usuário precisa tocar no botão para visualizar os itens pesquisados. Pensando um pouco na usabilidade, seria muito legal se o histórico fosse apresentado na parte inferior da tela inicial pois assim eliminariamos uma ação, o espaço da tela seriam melhor aproveitado e por consequência mais valor seria entregue ao usuário.

---

### Resumo

Parabéns, a solução atendeu a todos os requisitos! 👍 

O ponto mais positivo é a estrutura e organização do código-fonte. Existe uma camada de serviço, um gerenciador de conteúdo, a lista utiliza o RecyclerView com um ViewHolder, etc. É fácil entender e manter o app.

Talvez o único ponto a ser melhorado seja a interpretação das especificações. Num cenário real sabemos que a especificação, quando existe, nem sempre é bem definida por isso esperamos que o desenvolvedor faça uma leitura do contexto e apresente uma solução.

---

Os testes se encerram ao final desta semana, portanto no ínicio da semana que vem estaremos enviando um feedback final.

Abraços.
